version: '3.1'
networks:
  ads_scan_explorer_network:
      name: ads_scan_explorer_network
      driver: bridge
services:
  ads_scan_explorer_pipeline:
    container_name: ads_scan_explorer_pipeline
    build: 
      context: ../../
      dockerfile: ./docker/pipeline/Dockerfile
    image: ads_scan_explorer_pipeline:latest
    volumes:
    - ../../:/app
    - /src/ADS_scans_sample/:/opt/ADS_scans_sample
    entrypoint: celery -A ADSScanExplorerPipeline.tasks worker
    environment:
      - SQLALCHEMY_URL='postgres://scan_explorer:scan_explorer@postgres:5432/scan_explorer_pipeline'
      # When 'True', no events are emitted to the broker via the webhook
      - TESTING_MODE=True
      # When 'True', it converts all the asynchronous calls into synchronous,
      # thus no need for rabbitmq, it does not forward to master
      # and it allows debuggers to run if needed:
      - CELERY_ALWAYS_EAGER=True
      - CELERY_EAGER_PROPAGATES_EXCEPTIONS=True
    networks:
      - ads_scan_explorer_network
